#!/bin/bash
# role for shadow

set -e

source /usr/local/sbin/logging-functions
source /usr/local/sbin/logfile-functions
source /usr/local/sbin/daemon-functions

src=/usr/local/src/shadow
env=/usr/local/python-environments/shadow-virtualenv

start()
{
    log_info "configuring shadow role."

    ############################ VIRTUALENV ############################

    $src/scripts/make_virtualenv.sh $env
    . $env/bin/activate

    if [[ -d /service/shadow ]]
    then
        ! sv reload shadow; sv up shadow
    else
        runit_service_create shadow nobody "${env}/bin/ginkgo $src/shadow.conf.py"
        while ! pgrep -x -f "runsv shadow" > /dev/null; do sleep 1; done
    fi
    sv stop shadow

    cp $src/scripts/init.d/shadow /etc/init.d/

    log_info "done."

    log_info "shadow service is created, but you have to start it yourself after modifying $src/shadow.conf.py"
}

stop()
{
    if [[ -d /service/shadow ]]; then ! sv stop shadow; fi
}

case "$1" in
    start)
        start
    ;;
    stop)
        stop
    ;;
    restart)
        stop
        start
    ;;
    *)
    ;;
esac
